// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://qkqlcdkcuobuqinvqggx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrcWxjZGtjdW9idXFpbnZxZ2d4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc5NDc1NjIsImV4cCI6MjA4MzUyMzU2Mn0.Nz-MY_4Jj11E1e4hBtQjFTcDX08xRxKPUI9Iq692WKY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);